allowBuilds:
  esbuild: true
minimumReleaseAge: 720
minimumReleaseAgeExclude:
  - "@biomejs/*"
  - "@lbenie/*"
  - vite
  # Renovate security update: sanitize-html@2.17.5
  - sanitize-html@2.17.5
publicHoistPattern:
  - "@biomejs/biome"
